baseurl = "https://example.com/"
title = "zhi"
theme = "hugo-theme-console"
languageCode = "en-us"

# For math
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true  # This to allow embed videos
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true  # This for math
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[taxonomies]
  category = "categories"
  tag = "tags"


[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  # Enable math
  math = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "research/"
  url = "research/"

  [[params.navlinks]]
  name = "photos/"
  url = "photos/"
